name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install yamllint
        run: pip install yamllint
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: xero_accounting.yaml
          config_data: |
            extends: default
            rules:
              line-length:
                level: warning
              trailing-spaces:
                level: warning
              indentation:
                level: warning
              colons:
                level: warning
              commas:
                level: warning
              new-line-at-end-of-file:
                level: warning
